import { useEffect, useState } from 'react';
import { ArrowUpRight, Clock3, Database, ShieldAlert } from 'lucide-react';
import { Link } from 'react-router-dom';
import { fetchModelMonitoring, fetchReviewCases } from '../api/client';
import { useApp } from '../context/AppContext';
import { Badge, PageGuide } from './ui/Primitives';
import { RiskTraceChart } from './ui/Charts';

const pct=v=>v==null?'—':`${(v*100).toFixed(1)}%`;
export default function AdminOperations(){
  const{transactions,audits,auditJobs,health,connectionStatus}=useApp();const[monitor,setMonitor]=useState(null);const[reviews,setReviews]=useState(null);
  useEffect(()=>{Promise.all([fetchModelMonitoring(24),fetchReviewCases({limit:100})]).then(([m,r])=>{setMonitor(m);setReviews(r)}).catch(()=>{})},[]);
  const p=monitor?.predictions;const h=monitor?.human_review;const open=reviews?.items?.filter(x=>x.status!=='resolved')||[];const failed=auditJobs.filter(j=>j.status==='failed');
  return <div className="ops-page"><PageGuide title="See system pressure, then act on the exception.">Risk movement shows model decisions over time. Review pressure shows where human work is waiting. Use the live demonstration control above to exercise the full pipeline.</PageGuide><section className="ops-statusline"><div><span className={`status-dot status-dot--${health}`}/><strong>Risk core {health}</strong></div><span>WebSocket {connectionStatus}</span><span>{p?.total??transactions.length} decisions / 24h</span><span>{open.length} unresolved reviews</span><span>{failed.length} failed audits</span></section>
  <section className="command-overview"><header><div><span className="eyebrow">24-hour operating window</span><h2>Decision system at a glance</h2></div><span>{monitor?.generated_at?new Date(monitor.generated_at).toLocaleString('en-GB',{timeZone:'UTC',hour12:false})+' UTC':'Loading live report…'}</span></header><div className="metric-rail"><div><span>Predictions</span><strong>{p?.total??transactions.length}</strong><small>{p?.blocked??0} blocked</small></div><div><span>Blocked rate</span><strong>{pct(p?.blocked_rate)}</strong><small>threshold {monitor?.model?.decision_threshold?.toFixed(3)??'—'}</small></div><div><span>Review completion</span><strong>{pct(h?.decision_completion_rate)}</strong><small>{h?.open??0} open · {h?.in_review??0} active</small></div><div><span>Audit records</span><strong>{audits.length}</strong><small>{auditJobs.filter(j=>j.status==='pending'||j.status==='processing').length} compiling</small></div><div><span>Score drift</span><strong>{monitor?.score_drift?.psi?.toFixed(3)??'—'}</strong><small>{monitor?.score_drift?.level?.replaceAll('_',' ')??'insufficient data'}</small></div></div></section>
  <section className="operations-grid"><div className="ops-plot"><header><div><span className="eyebrow">Interactive decision history</span><h3>How ensemble risk moved across recent transactions</h3><p>Hover a point for its transaction, amount, score and outcome. Coral points crossed the decision gate.</p></div><Link to="/app/transactions">Open full stream <ArrowUpRight size={13}/></Link></header><RiskTraceChart transactions={transactions} threshold={monitor?.model?.decision_threshold??.95}/></div><div className="pressure-panel"><header><div><span className="eyebrow">Human workload</span><h3>Where cases are waiting</h3><p>Longer tracks indicate a larger share of the current review window.</p></div></header>{[['Unassigned',h?.open??0],['Analyst review',h?.in_review??0],['Admin approval',h?.awaiting_approval??0],['Finalized',h?.resolved??0]].map(([name,value])=><div key={name} tabIndex="0"><span>{name}</span><i><b style={{width:`${Math.min(100,value/Math.max(1,h?.cases_created||1)*100)}%`}}/></i><strong>{value}</strong><output>{value} of {h?.cases_created??0} review cases</output></div>)}<Link className="text-action" to="/app/reviews">Enter review control <ArrowUpRight size={13}/></Link></div></section>
  <section className="exception-ledger"><header><div><span className="eyebrow">Exceptions</span><h3>Items requiring operational attention</h3></div></header><div>{failed.length?<>{failed.slice(0,8).map(j=><div key={j.id}><Database size={14}/><span><strong>Audit compilation failed</strong><small className="mono">{j.transaction_id}</small></span><Badge tone="critical">{j.attempts} attempts</Badge></div>)}</>:open.slice(0,8).map(c=><div key={c.id}><ShieldAlert size={14}/><span><strong>{c.priority} review case</strong><small className="mono">{c.transaction_id}</small></span><Badge tone={c.priority==='critical'?'critical':'warning'}>{c.status.replaceAll('_',' ')}</Badge></div>)}{!failed.length&&!open.length&&<div><Clock3 size={14}/><span><strong>No active exceptions</strong><small>The operational queues are clear.</small></span></div>}</div></section></div>
}
