import { useEffect, useState } from 'react';
import { Activity } from 'lucide-react';
import { fetchModelMonitoring } from '../api/client';
import { Badge, EmptyState, PageGuide } from './ui/Primitives';
import { DistributionChart, StabilityGauge } from './ui/Charts';

const percent=(value)=>value==null?'—':`${(value*100).toFixed(2)}%`;
export default function ModelHealth(){
  const[hours,setHours]=useState(24);const[data,setData]=useState(null);const[error,setError]=useState('');
  useEffect(()=>{setData(null);setError('');fetchModelMonitoring(hours).then(setData).catch(requestError=>setError(requestError.message))},[hours]);
  if(error)return <EmptyState error title="Monitoring unavailable" message={error}/>;
  const predictions=data?.predictions,reviews=data?.human_review,drift=data?.score_drift,threshold=data?.model?.decision_threshold??.95;
  const interpretation=drift?.level==='stable'?'The score distribution remains close to the previous window.':drift?.level==='moderate_shift'?'Prediction behavior has moved enough to deserve investigation.':drift?.level==='significant_shift'?'The score distribution changed materially; inspect data and feature inputs.':'A second full comparison window is required before drift can be calculated.';
  return <div className="ops-page"><PageGuide title="Is the model behaving differently from its recent baseline?">Distribution shows where risk scores cluster. Stability compares that shape with the preceding period. Movement toward higher bands increases intervention pressure.</PageGuide><section className="ops-statusline"><div><Activity size={16}/><strong>{data?.model?.name?.replaceAll('_',' ')||'Ensemble model'}</strong></div><span>Decision boundary {(threshold*100).toFixed(2)}%</span><span>{predictions?.total??0} predictions</span><select value={hours} onChange={event=>setHours(Number(event.target.value))}><option value="24">Last 24 hours</option><option value="168">Last 7 days</option><option value="720">Last 30 days</option></select></section>
  <section className="health-header"><div><span className="eyebrow">Population stability index</span><h2>{drift?.level?.replaceAll('_',' ')||'Loading monitoring window'}</h2><p>{interpretation}</p><small>{drift?.current_sample_size??0} current · {drift?.previous_sample_size??0} baseline · minimum {drift?.minimum_sample_size??30} each</small></div><StabilityGauge psi={drift?.psi} level={drift?.level}/></section>
  <section className="monitor-grid"><div className="distribution-plot"><header><div><span className="eyebrow">Interactive score distribution</span><h3>Where predictions fall across the risk range</h3><p>Hover or focus a band for its count and share of this monitoring window.</p></div></header><DistributionChart buckets={predictions?.score_buckets||[]} threshold={threshold}/></div><div className="model-readout"><header><div><span className="eyebrow">Operational interpretation</span><h3>Outcomes worth watching</h3></div></header>{[['Average risk',percent(predictions?.average_risk_score),'Typical model confidence in this window.'],['Blocked rate',percent(predictions?.blocked_rate),'Share that crossed the deployed gate.'],['Review coverage',percent(reviews?.case_coverage_rate),'Blocked decisions represented by a case.'],['False-positive rate',percent(reviews?.false_positive_rate),'Final decisions that reversed the block.'],['Recommendation completion',percent(reviews?.decision_completion_rate),'Cases with an administrator verdict.'],['P95 resolution',reviews?.p95_resolution_seconds==null?'—':`${Math.round(reviews.p95_resolution_seconds)}s`,'Time within which 95% of cases finished.']].map(([name,value,help])=><div key={name} tabIndex="0"><span>{name}<small>{help}</small></span><strong className="mono">{value}</strong></div>)}</div></section><section className="feature-line"><span>Monitored input dimensions</span>{data?.model?.feature_dimensions?.map(item=><Badge key={item} tone="neutral">{item.replaceAll('_',' ')}</Badge>)}</section></div>;
}
